server:
  port: 1053
  udpThreadPool: 20
  tcpThreadPool: 4
  webPort: 8044

cache:
  enabled: true
  maxCacheEntries: 1000
  rewarm: true
  maxRewarmCount: 5

resolver:
  tlsPoolSize: 5
  multiplier: 3 #how many upstreams we will reach on each active remote query
  upstreams:
    #- ip: "1.1.1.1"
    #  port: 53
    #  protocol: "udp"
    #- ip: "8.8.8.8"
    #  port: 53
    #  protocol: "udp"
    #- ip: "9.9.9.9"
    #  port: 53
    #  protocol: "udp"
    #- ip: "8.8.4.4"
    #  port: 53
    #  protocol: "udp"
    - ip: "1.1.1.1"
      port: 853
      protocol: "dot"
      tlsAuthName: "cloudflare-dns.com"
    - ip: "8.8.8.8"
      port: 853
      protocol: "dot"
      tlsAuthName: "dns.google"
    - ip: "8.8.4.4"
      port: 853
      protocol: "dot"
      tlsAuthName: "dns.google"
    - ip: "9.9.9.9"
      port: 853
      protocol: "dot"
      tlsAuthName: "dns.quad9.net"
  localMappings:
    - domain: "karpov"
      ip: "192.168.68.113"
    - domain: "cronicle.intranet"
      ip: "192.168.68.126"
  blocklists:
    - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
    - "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/Bets.txt"
    #- "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/youtube.txt"
    #- "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/Malicious.txt"
    #- "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/ransomware.txt"
    #- "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/spam.mails.txt"
    #- "https://raw.githubusercontent.com/zangadoprojets/pi-hole-blocklist/main/Telemetry.txt"
    #- "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
