server:
  port: 53
  udpThreadPool: 10
  tcpThreadPool: 3
  webPort: 8044
  httpThreadPool: 10

cache:
  enabled: true
  maxCacheEntries: 1000
  rewarm: true
  maxRewarmCount: 5

resolver:
  multiplier: 3
  upstreams:
    - host: "cloudflare-dns.com"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.google"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.quad9.net"
      port: 443
      protocol: "doh"
      path: "/dns-query"
    - host: "dns.adguard.com"
      port: 443
      protocol: "doh"
      path: "/dns-query"

  localMappings:

  blocklists:
    - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

