package com.allanvital.dnsao.dns.recursive;

/**
 * @author Allan Vital (https://allanvital.com)
 */
public enum RecursiveMetric {

    SESSION_STARTED,
    SESSION_SUCCEEDED,
    SESSION_NXDOMAIN,
    SESSION_NODATA,
    SESSION_FAILED,
    SESSION_ELAPSED_MS_SUM,
    SESSION_STEP_SUM,

    WALK_STEP,
    FINAL_STEP,
    REFERRAL_FOLLOWED,
    CNAME_FOLLOWED,
    HELPER_RESOLVE_A,
    HELPER_RESOLVE_AAAA,

    CACHE_HIT_NS,
    CACHE_PUT_NS,
    CACHE_HIT_FINAL,
    CACHE_PUT_FINAL,

    RACE_STARTED,
    RACE_WON,
    RACE_TIMEOUT,
    RACE_LOSERS_CANCELLED,
    RACE_CANDIDATE_SUM,
    RACE_FANOUT_SUM,

    UDP_REJECTED_WRONG_SOURCE,
    UDP_REJECTED_WRONG_ID,
    UDP_REJECTED_WRONG_QUESTION,
    UDP_REJECTED_MISSING_QR,

    TCP_FALLBACK_STARTED,
    TCP_FALLBACK_SUCCEEDED,
    TCP_FALLBACK_FAILED,

    DNSSEC_DOWNGRADE_ATTEMPTED,
    DNSSEC_DOWNGRADE_SUCCEEDED

}
