name: Build 'latest' from prod tag (GHCR)

on:
  workflow_dispatch:
  workflow_call: {}

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/dnsao
  DOCKERFILE: docker/Dockerfile
  CONTEXT: .

concurrency:
  group: latest
  cancel-in-progress: false

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prod tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/prod
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (latest only)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
          flavor: |
            latest=true

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
