name: Maintenance - GHCR cleanup (untagged only, SAFE)

on:
  workflow_dispatch:
  workflow_call: {}

permissions:
  packages: write
  contents: read

concurrency:
  group: ghcr-cleanup
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged container versions (keep a buffer!)
        uses: actions/delete-package-versions@v5
        with:
          package-name: dnsao
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 10 
